# coding: utf-8

"""
    LABO3

    MANAGE THE FILES  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dossiers_api import DossiersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDossiersApi(unittest.TestCase):
    """DossiersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.dossiers_api.DossiersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cours_idcours_seances_idseance_dossiers_iddossier_delete(self):
        """Test case for cours_idcours_seances_idseance_dossiers_iddossier_delete

        Delete a dossier  # noqa: E501
        """
        pass

    def test_get_dossier_by_id(self):
        """Test case for get_dossier_by_id

        Get dossier by ID  # noqa: E501
        """
        pass

    def test_get_dosssiers(self):
        """Test case for get_dosssiers

        Get liste de dossiers dans seances  # noqa: E501
        """
        pass

    def test_post_dossier(self):
        """Test case for post_dossier

        Creer dossier dans une seance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
