# coding: utf-8

"""
    LABO3

    MANAGE THE FILES  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.fichiers_api import FichiersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFichiersApi(unittest.TestCase):
    """FichiersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.fichiers_api.FichiersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cours_idcours_seances_idseance_dossiers_iddossier_fichiers_post(self):
        """Test case for cours_idcours_seances_idseance_dossiers_iddossier_fichiers_post

        Create a new file for a specific session  # noqa: E501
        """
        pass

    def test_cours_idcours_seances_idseance_fichiers_get(self):
        """Test case for cours_idcours_seances_idseance_fichiers_get

        Retrieve files for a specific session  # noqa: E501
        """
        pass

    def test_cours_idcours_seances_idseance_fichiers_idfichier_delete(self):
        """Test case for cours_idcours_seances_idseance_fichiers_idfichier_delete

        Delete a file by ID  # noqa: E501
        """
        pass

    def test_cours_idcours_seances_idseance_fichiers_post(self):
        """Test case for cours_idcours_seances_idseance_fichiers_post

        Create a new file for a specific session  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
