# coding: utf-8

"""
    LABO3

    MANAGE THE FILES  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.seances_api import SeancesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSeancesApi(unittest.TestCase):
    """SeancesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.seances_api.SeancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_seance(self):
        """Test case for delete_seance

        Delete a seance by ID  # noqa: E501
        """
        pass

    def test_get_seances(self):
        """Test case for get_seances

        Get seances pour a cours  # noqa: E501
        """
        pass

    def test_get_seances_by_id(self):
        """Test case for get_seances_by_id

        Get a seance by ID  # noqa: E501
        """
        pass

    def test_get_seances_by_module(self):
        """Test case for get_seances_by_module

        Get liste de seance by module  # noqa: E501
        """
        pass

    def test_get_seances_by_semaine(self):
        """Test case for get_seances_by_semaine

        Get liste de seance by semaine  # noqa: E501
        """
        pass

    def test_post_seance(self):
        """Test case for post_seance

        Create a new seance in a cours  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
