# coding: utf-8

"""
    LABO3

    MANAGE THE FILES  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cours_api import CoursApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCoursApi(unittest.TestCase):
    """CoursApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cours_api.CoursApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_cours(self):
        """Test case for delete_cours

        Delete a cours by ID  # noqa: E501
        """
        pass

    def test_get_cours(self):
        """Test case for get_cours

        Retrieve a list of all courses  # noqa: E501
        """
        pass

    def test_get_cours_by_id(self):
        """Test case for get_cours_by_id

        Retrieve a cours by ID  # noqa: E501
        """
        pass

    def test_get_cours_by_tag(self):
        """Test case for get_cours_by_tag

        Retrieve a Cours by Tag  # noqa: E501
        """
        pass

    def test_post_cours(self):
        """Test case for post_cours

        Create a new cours  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
