# coding: utf-8

# flake8: noqa

"""
    LABO3

    MANAGE THE FILES  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.cours_api import CoursApi
from swagger_client.api.dossiers_api import DossiersApi
from swagger_client.api.fichiers_api import FichiersApi
from swagger_client.api.seances_api import SeancesApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
